/* ═══════════════════════════════════════════════════
   MOCK DATA — Patients & Cases
   Shared across PatientsPage, PatientDetailsPage,
   ReservedCasesPage, and CompletedCasesPage.
   ═══════════════════════════════════════════════════ */

export const MOCK_PATIENTS = [
  {
    id: 1,
    name: 'Ahmed Hassan',
    age: 34,
    phone: '+20 100 123 4567',
    gender: 'Male',
    registrationDate: '08 Jun 2026',
    status: 'active',
    medicalHistory: 'Hypertension (controlled). No known drug allergies.',
    notes: 'Prefers morning appointments. Slightly anxious about needles.',
    cases: [
      {
        id: 101,
        toothNumber: '16',
        diagnosis: 'Caries – Class II',
        treatmentType: 'Composite Filling',
        status: 'available',
        reservationStatus: 'Not Reserved',
        assignedStudent: '—',
        reservedDate: null,
        completionDate: null,
        timeline: [
          { stage: 'Case Created', date: '01 Jun 2026', done: true },
          { stage: 'Reserved', date: null, done: false },
          { stage: 'Treatment Started', date: null, done: false },
          { stage: 'Completed', date: null, done: false },
        ],
      },
      {
        id: 102,
        toothNumber: '26',
        diagnosis: 'Gingivitis',
        treatmentType: 'Scaling & Polishing',
        status: 'completed',
        reservationStatus: 'Completed',
        assignedStudent: 'Yasmin El-Sayed',
        reservedDate: '03 Jun 2026',
        completionDate: '07 Jun 2026',
        timeline: [
          { stage: 'Case Created', date: '02 Jun 2026', done: true },
          { stage: 'Reserved', date: '03 Jun 2026', done: true },
          { stage: 'Treatment Started', date: '05 Jun 2026', done: true },
          { stage: 'Completed', date: '07 Jun 2026', done: true },
        ],
      },
    ],
  },
  {
    id: 2,
    name: 'Sara Khaled',
    age: 27,
    phone: '+20 101 234 5678',
    gender: 'Female',
    registrationDate: '07 Jun 2026',
    status: 'waiting',
    medicalHistory: 'No significant medical history reported.',
    notes: 'Requested female student if possible.',
    cases: [
      {
        id: 103,
        toothNumber: '21',
        diagnosis: 'Root Canal Treatment',
        treatmentType: 'Endodontic Therapy',
        status: 'reserved',
        reservationStatus: 'Reserved',
        assignedStudent: 'Mona Tarek',
        reservedDate: '08 Jun 2026',
        completionDate: null,
        timeline: [
          { stage: 'Case Created', date: '07 Jun 2026', done: true },
          { stage: 'Reserved', date: '08 Jun 2026', done: true },
          { stage: 'Treatment Started', date: null, done: false },
          { stage: 'Completed', date: null, done: false },
        ],
      },
    ],
  },
  {
    id: 3,
    name: 'Mohamed Ali',
    age: 45,
    phone: '+20 102 345 6789',
    gender: 'Male',
    registrationDate: '06 Jun 2026',
    status: 'completed',
    medicalHistory: 'Type 2 Diabetes (managed with medication).',
    notes: 'Follow up in 6 months for extraction site review.',
    cases: [
      {
        id: 104,
        toothNumber: '36',
        diagnosis: 'Extraction – Impacted',
        treatmentType: 'Surgical Extraction',
        status: 'completed',
        reservationStatus: 'Completed',
        assignedStudent: 'Hadi Samir',
        reservedDate: '01 Jun 2026',
        completionDate: '06 Jun 2026',
        timeline: [
          { stage: 'Case Created', date: '30 May 2026', done: true },
          { stage: 'Reserved', date: '01 Jun 2026', done: true },
          { stage: 'Treatment Started', date: '04 Jun 2026', done: true },
          { stage: 'Completed', date: '06 Jun 2026', done: true },
        ],
      },
    ],
  },
  {
    id: 4,
    name: 'Nour Ibrahim',
    age: 22,
    phone: '+20 103 456 7890',
    gender: 'Female',
    registrationDate: '05 Jun 2026',
    status: 'reserved',
    medicalHistory: 'No known allergies.',
    notes: 'Student dentistry program — peer referral.',
    cases: [
      {
        id: 105,
        toothNumber: '11',
        diagnosis: 'Crown Restoration',
        treatmentType: 'Porcelain Crown',
        status: 'reserved',
        reservationStatus: 'Reserved',
        assignedStudent: 'Hadi Samir',
        reservedDate: '06 Jun 2026',
        completionDate: null,
        timeline: [
          { stage: 'Case Created', date: '05 Jun 2026', done: true },
          { stage: 'Reserved', date: '06 Jun 2026', done: true },
          { stage: 'Treatment Started', date: null, done: false },
          { stage: 'Completed', date: null, done: false },
        ],
      },
    ],
  },
  {
    id: 5,
    name: 'Layla Mahmoud',
    age: 38,
    phone: '+20 104 567 8901',
    gender: 'Female',
    registrationDate: '04 Jun 2026',
    status: 'completed',
    medicalHistory: 'Penicillin allergy — alternative antibiotics required.',
    notes: 'Very punctual, prefers afternoon slots.',
    cases: [
      {
        id: 106,
        toothNumber: '46',
        diagnosis: 'Caries – Class I',
        treatmentType: 'Composite Filling',
        status: 'completed',
        reservationStatus: 'Completed',
        assignedStudent: 'Dina Fathy',
        reservedDate: '29 May 2026',
        completionDate: '03 Jun 2026',
        timeline: [
          { stage: 'Case Created', date: '28 May 2026', done: true },
          { stage: 'Reserved', date: '29 May 2026', done: true },
          { stage: 'Treatment Started', date: '01 Jun 2026', done: true },
          { stage: 'Completed', date: '03 Jun 2026', done: true },
        ],
      },
      {
        id: 107,
        toothNumber: '47',
        diagnosis: 'Pulp Capping',
        treatmentType: 'Indirect Pulp Capping',
        status: 'completed',
        reservationStatus: 'Completed',
        assignedStudent: 'Omar Saleh',
        reservedDate: '30 May 2026',
        completionDate: '04 Jun 2026',
        timeline: [
          { stage: 'Case Created', date: '29 May 2026', done: true },
          { stage: 'Reserved', date: '30 May 2026', done: true },
          { stage: 'Treatment Started', date: '02 Jun 2026', done: true },
          { stage: 'Completed', date: '04 Jun 2026', done: true },
        ],
      },
    ],
  },
  {
    id: 6,
    name: 'Omar Farouk',
    age: 29,
    phone: '+20 105 678 9012',
    gender: 'Male',
    registrationDate: '03 Jun 2026',
    status: 'waiting',
    medicalHistory: 'No significant medical history reported.',
    notes: 'Works night shifts — needs flexible scheduling.',
    cases: [
      {
        id: 108,
        toothNumber: '24',
        diagnosis: 'Pulp Capping',
        treatmentType: 'Direct Pulp Capping',
        status: 'available',
        reservationStatus: 'Not Reserved',
        assignedStudent: '—',
        reservedDate: null,
        completionDate: null,
        timeline: [
          { stage: 'Case Created', date: '03 Jun 2026', done: true },
          { stage: 'Reserved', date: null, done: false },
          { stage: 'Treatment Started', date: null, done: false },
          { stage: 'Completed', date: null, done: false },
        ],
      },
    ],
  },
  {
    id: 7,
    name: 'Rania Sayed',
    age: 31,
    phone: '+20 106 789 0123',
    gender: 'Female',
    registrationDate: '02 Jun 2026',
    status: 'completed',
    medicalHistory: 'Asthma — uses inhaler as needed.',
    notes: 'Bring inhaler reminder card to appointments.',
    cases: [
      {
        id: 109,
        toothNumber: '14',
        diagnosis: 'Fixed Partial Denture',
        treatmentType: 'Bridge Placement',
        status: 'completed',
        reservationStatus: 'Completed',
        assignedStudent: 'Mona Tarek',
        reservedDate: '27 May 2026',
        completionDate: '02 Jun 2026',
        timeline: [
          { stage: 'Case Created', date: '25 May 2026', done: true },
          { stage: 'Reserved', date: '27 May 2026', done: true },
          { stage: 'Treatment Started', date: '30 May 2026', done: true },
          { stage: 'Completed', date: '02 Jun 2026', done: true },
        ],
      },
    ],
  },
  {
    id: 8,
    name: 'Khaled Nasser',
    age: 50,
    phone: '+20 107 890 1234',
    gender: 'Male',
    registrationDate: '01 Jun 2026',
    status: 'active',
    medicalHistory: 'High blood pressure, on beta-blockers.',
    notes: 'Long-time patient, transferred from another clinic.',
    cases: [
      {
        id: 110,
        toothNumber: '31',
        diagnosis: 'Scaling & Root Planing',
        treatmentType: 'Periodontal Therapy',
        status: 'available',
        reservationStatus: 'Not Reserved',
        assignedStudent: '—',
        reservedDate: null,
        completionDate: null,
        timeline: [
          { stage: 'Case Created', date: '01 Jun 2026', done: true },
          { stage: 'Reserved', date: null, done: false },
          { stage: 'Treatment Started', date: null, done: false },
          { stage: 'Completed', date: null, done: false },
        ],
      },
      {
        id: 111,
        toothNumber: '32',
        diagnosis: 'Tooth Discoloration',
        treatmentType: 'Professional Whitening',
        status: 'reserved',
        reservationStatus: 'Reserved',
        assignedStudent: 'Yasmin El-Sayed',
        reservedDate: '09 Jun 2026',
        completionDate: null,
        timeline: [
          { stage: 'Case Created', date: '08 Jun 2026', done: true },
          { stage: 'Reserved', date: '09 Jun 2026', done: true },
          { stage: 'Treatment Started', date: null, done: false },
          { stage: 'Completed', date: null, done: false },
        ],
      },
    ],
  },
  {
    id: 9,
    name: 'Mona Adel',
    age: 26,
    phone: '+20 108 901 2345',
    gender: 'Female',
    registrationDate: '31 May 2026',
    status: 'reserved',
    medicalHistory: 'No known allergies.',
    notes: 'Currently mid-treatment — handle with care during transfers.',
    cases: [
      {
        id: 112,
        toothNumber: '45',
        diagnosis: 'Crown Restoration',
        treatmentType: 'Zirconia Crown',
        status: 'reserved',
        reservationStatus: 'In Progress',
        assignedStudent: 'Hadi Samir',
        reservedDate: '02 Jun 2026',
        completionDate: null,
        timeline: [
          { stage: 'Case Created', date: '31 May 2026', done: true },
          { stage: 'Reserved', date: '02 Jun 2026', done: true },
          { stage: 'Treatment Started', date: '09 Jun 2026', done: true },
          { stage: 'Completed', date: null, done: false },
        ],
      },
    ],
  },
  {
    id: 10,
    name: 'Tarek Younis',
    age: 41,
    phone: '+20 109 012 3456',
    gender: 'Male',
    registrationDate: '30 May 2026',
    status: 'waiting',
    medicalHistory: 'No significant medical history reported.',
    notes: 'First-time patient — verify contact details at next visit.',
    cases: [
      {
        id: 113,
        toothNumber: '17',
        diagnosis: 'Caries – Class III',
        treatmentType: 'Composite Filling',
        status: 'available',
        reservationStatus: 'Not Reserved',
        assignedStudent: '—',
        reservedDate: null,
        completionDate: null,
        timeline: [
          { stage: 'Case Created', date: '30 May 2026', done: true },
          { stage: 'Reserved', date: null, done: false },
          { stage: 'Treatment Started', date: null, done: false },
          { stage: 'Completed', date: null, done: false },
        ],
      },
    ],
  },
];

/* Convenience lookup */
export function getPatientById(id) {
  return MOCK_PATIENTS.find((p) => String(p.id) === String(id));
}
